#!/bin/sh

pgrep -x transmission-da >/dev/null || (transmission-daemon && notify-send "Starting transmission daemon...")

transmission-remote -a "$@" && notify-send "🔽 Transmission-dameon" "Torrent added."
