#!/bin/zsh

#######################################################
# script that auto commits in specified folder repos  #
#######################################################

echo "$0" | systemd-cat

gitSyncDir=$1

pullRepo() {
	typeset syncDir=$1
	cd $syncDir
	tsp sh -c "cd $syncDir; git diff-index --quiet HEAD -- || (git add .;git commit -m 'vim autocommit' | systemd-cat; git push | systemd-cat; notify-send 'Git' 'Succesfully pushed $syncDir')"
}

if [[ -d $gitSyncDir ]]; then
	cd $gitSyncDir
	set -A dirs $(ls -d $PWD/*)
	for syncDir in $dirs; pullRepo "$syncDir";
else
	echo "Bad path passed $gitSyncDir" 1>&2
	exit 1
fi

