#!/bin/bash

([[ -z "$1" ]] && dir="$HOME") || dir="$1"
cd $dir
du -shc \
	--exclude=Downloads \
	--exclude=.cache \
	--exclude='VirtualBox VMs' \
	--exclude=code \
	--exclude=Installs \
	--exclude=Projects \
	--exclude=.minikube \
	--exclude=.local \
	--exclude=.ivy2 \
	--exclude=.Idea* \
	--exclude=.sbt \
	--exclude=.m2 \
	--exclude=.npm \
	--exclude=.mozilla \
	--exclude=.GlobalProtect \
	--exclude=.kube \
	--exclude=.gem \
	--exclude=chromium \
	--exclude=Slack \
	--exclude=BraveSoftware \
	--exclude=.java \
	--exclude=.idea-build \
	--exclude=.newsboat \
	--exclude=.fzf \
	--exclude=.IntelliJ* \
	--exclude=Downloaded -- $(ls -A) | sort -h
