#!/bin/zsh

############################
#  synchronizes git repos  #
############################

scriptName=${0:t}

usage() { 
	echo "Usage: $scriptName -a <pull|push> -r <repositoriesFolder>" 1>&2
	echo ""
	echo "example: $scriptName -a pull -r ~/Documents/wiki" 1>&2
	exit 1
}

while getopts ":r:a:" o; do
	case "${o}" in
		r)
			gitReposDir=${OPTARG}
			;;
		a)
			action=${OPTARG}
			[[ $action == "push" || $action == "pull" ]] || usage
			;;
		*)
			usage
			;;
	esac
done

[[ -z "$gitReposDir" || -z "$action" ]] && usage
[[ ! -d $gitReposDir ]] && (echo "Bad path passed $gitSyncDir" 1>&2; exit 1)

cd $gitReposDir
set -A dirs $(ls -d $PWD/*)

case "$action" in
	pull)
		for syncDir in $dirs; tsp zsh -c "syncGitPull \"$syncDir\""
		;;
	push)
		for syncDir in $dirs; tsp zsh -c "syncGitPush \"$syncDir\""
		;;
esac
