#!/bin/zsh

#######################################################
# script running torrent-remote-cli as stand alone    #
#######################################################

pgrep -x transmission-da >/dev/null || (transmission-daemon && notify-send "Starting transmission daemon...")

nohup st -e tremc
