#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	less="less --IGNORE-CASE -R" \
	yay="yay --color=always"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ll="ls -la" \
	pm="sudo pacman --color=always" \
	g="git" \
	gp="git pull" \
	gcm="git checkout master" \
	gca="git commit -v -a" \
	tremc="transmission-remote-cli" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	sbtDependencyTree="sbt dependencyTree | less -R" \
	sbtDependencyBrowseGraph="sbt dependencyBrowseGraph" \
	sbtDependencyBrowseTree="sbt dependencyBrowseTree" \
	sbtDependencyStats="sbt dependencyStats | less -R" \
	sbtWhatDependsOn="print -z 'sbt \"whatDependsOn com.google.protobuf protobuf-java\"'" \
	newscalaproject="echo $1"

vf(){ fzf | xargs -r -I % $EDITOR % ;}
se(){ find ~/.config/ -type f | fzf | xargs -r $EDITOR ;}
sev(){ searchVim $1 }
