#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	pm="sudo pacman" \
	g="git" \
	gp="git pull" \
	gcm="git checkout master" \
	gca="git commit -v -a" \
	tremc="transmission-remote-cli" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \

vf(){ fzf | xargs -r -I % $EDITOR % ;}
#se(){ du -a ~/.config/ | awk '{print $2}' | fzf | xargs -r $EDITOR ;}
se(){ find ~/.config/ -type f | fzf | xargs -r $EDITOR ;}
